# These are supported funding model platforms

Revolut
https://revolut.me/rhc94/

Crypto
BTC on Bitcoin network: bc1qzajwxuuv8p72mtlc07kgq5fmsgpnsyxg8qg6st
ETH on Ethereum network: 0x4aAFC9AD27fB8767E668AB9a6E16d072d8E8A52D
USDT on Ethereum network: 0x4aAFC9AD27fB8767E668AB9a6E16d072d8E8A52D
USDC on Ethereum network: 0x4aAFC9AD27fB8767E668AB9a6E16d072d8E8A52D
